version: "3.8"

services:
  bs_nginx:
    container_name: gs_nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3200:3200"
      - "3300:3300"
    depends_on:
      - bs_php_fpm
    restart: unless-stopped

  bs_php_fpm:
    user: 1000:1000
    container_name: bs_php_fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - bs_mysql

  bs_php_cli:
    user: 1000:1000
    container_name: bs_php_cli
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - bs_mysql

  bs_mysql:
    container_name: bs_mysql
    image: bitnami/mysql:latest
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - bs_mysql-db-data:/var/lib/mysql/
      - ./docker/mysql/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

networks:
  default:
    external: true
    name: bs_network

volumes:
  bs_mysql-db-data:
